import { IconType } from "react-icons/lib";
import {
  SiAmazonwebservices,
  SiAmazondynamodb,
  SiAmazonsqs,
  SiAndroid,
  SiAngular,
  SiAnsible,
  SiApacheairflow,
  SiApachecassandra,
  SiApachecordova,
  SiApachecouchdb,
  SiApacheflink,
  SiApachehadoop,
  SiApachehive,
  SiApachekafka,
  SiApachemaven,
  SiApachespark,
  SiArchlinux,
  SiArgo,
  SiAvajs,
  SiBabel,
  SiBackbonedotjs,
  SiBitbucket,
  SiBootstrap,
  SiC,
  SiChakraui,
  SiChai,
  SiChef,
  SiCircleci,
  SiClojure,
  SiCodeigniter,
  SiComposer,
  SiConsul,
  SiCplusplus,
  SiCss3,
  SiCypress,
  SiDart,
  SiDatadog,
  SiDebian,
  SiDeno,
  SiDigitalocean,
  SiDjango,
  SiDocker,
  SiElasticsearch,
  SiElasticstack,
  SiElixir,
  SiEmberdotjs,
  SiEslint,
  SiEthereum,
  SiEthers,
  SiExpress,
  SiFastapi,
  SiFastify,
  SiFedora,
  SiFigma,
  SiFlask,
  SiFlutter,
  SiFlydotio,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGitlab,
  SiGnubash,
  SiGo,
  SiGooglecloud,
  SiGradle,
  SiGrafana,
  SiGraphql,
  SiHaskell,
  SiHelm,
  SiHeroku,
  SiHtml5,
  SiInsomnia,
  SiIonic,
  SiIos,
  SiIpfs,
  SiIstio,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiJetpackcompose,
  SiJson,
  SiJsonwebtokens,
  SiJunit5,
  SiKeras,
  SiKotlin,
  SiKubernetes,
  SiLaravel,
  SiLess,
  SiLinux,
  SiLinuxcontainers,
  SiMacos,
  SiMariadb,
  SiMeilisearch,
  SiMocha,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNatsdotio,
  SiNeo4J,
  SiNestjs,
  SiNetlify,
  SiNewrelic,
  SiNextdotjs,
  SiNodedotjs,
  SiNomad,
  SiNpm,
  SiNumpy,
  SiNuxtdotjs,
  SiOpencv,
  SiOpenid,
  SiOracle,
  SiOwasp,
  SiPandas,
  SiPerforce,
  SiPhoenixframework,
  SiPhp,
  SiPlanetscale,
  SiPodman,
  SiPoetry,
  SiPolygon,
  SiPnpm,
  SiPostgresql,
  SiPostman,
  SiPresto,
  SiPrettier,
  SiPrometheus,
  SiPulumi,
  SiPuppet,
  SiPuppeteer,
  SiPython,
  SiPytest,
  SiPytorch,
  SiQuarkus,
  SiR,
  SiRabbitmq,
  SiReact,
  SiRedhat,
  SiRedhatopenshift,
  SiRedis,
  SiRollupdotjs,
  SiRuby,
  SiRubyonrails,
  SiRust,
  SiSass,
  SiScala,
  SiScikitlearn,
  SiSelenium,
  SiSentry,
  SiSolid,
  SiSolidity,
  SiSolana,
  SiSpacy,
  SiSplunk,
  SiSpringboot,
  SiSqlite,
  SiStorybook,
  SiStyledcomponents,
  SiSubversion,
  SiSupabase,
  SiSvelte,
  SiSwagger,
  SiSwift,
  SiSymfony,
  SiTailwindcss,
  SiTeamcity,
  SiTensorflow,
  SiTerraform,
  SiTestinglibrary,
  SiTravisci,
  SiTrpc,
  SiTurbo,
  SiTypescript,
  SiUbuntu,
  SiVault,
  SiVercel,
  SiVite,
  SiVitest,
  SiVmware,
  SiVirtualbox,
  SiVuedotjs,
  SiWebpack,
  SiWeb3Dotjs,
  SiXml,
  SiYarn,
  SiPerl,
} from "react-icons/si";
export const SKILL_ICONS: Record<string, IconType> = {
  // Languages
  JavaScript: SiJavascript,
  TypeScript: SiTypescript,
  Python: SiPython,
  C: SiC,
  "C++": SiCplusplus,
  Go: SiGo,
  Rust: SiRust,
  PHP: SiPhp,
  Ruby: SiRuby,
  Kotlin: SiKotlin,
  Swift: SiSwift,
  Dart: SiDart,
  Scala: SiScala,
  Haskell: SiHaskell,
  Perl: SiPerl,
  R: SiR,
  Elixir: SiElixir,
  Clojure: SiClojure,
  Bash: SiGnubash,

  // Web Frontend
  HTML: SiHtml5,
  CSS: SiCss3,
  Sass: SiSass,
  Less: SiLess,
  Bootstrap: SiBootstrap,
  TailwindCSS: SiTailwindcss,
  "Material-UI": SiMui,
  "Chakra UI": SiChakraui,
  "Styled Components": SiStyledcomponents,

  // JavaScript Frameworks
  React: SiReact,
  "Next.js": SiNextdotjs,
  "Vue.js": SiVuedotjs,
  "Nuxt.js": SiNuxtdotjs,
  Angular: SiAngular,
  Svelte: SiSvelte,
  SolidJS: SiSolid,
  "Ember.js": SiEmberdotjs,
  "Backbone.js": SiBackbonedotjs,

  // Backend Frameworks & Runtimes
  "Node.js": SiNodedotjs,
  Express: SiExpress,
  NestJS: SiNestjs,
  Fastify: SiFastify,
  Deno: SiDeno,
  Django: SiDjango,
  Flask: SiFlask,
  FastAPI: SiFastapi,
  "Spring Boot": SiSpringboot,
  Quarkus: SiQuarkus,
  Laravel: SiLaravel,
  Symfony: SiSymfony,
  CodeIgniter: SiCodeigniter,
  "Ruby on Rails": SiRubyonrails,
  "Phoenix Framework (Elixir)": SiPhoenixframework,

  // Databases
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MariaDB: SiMariadb,
  SQLite: SiSqlite,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  Cassandra: SiApachecassandra,
  CouchDB: SiApachecouchdb,
  DynamoDB: SiAmazondynamodb,
  Supabase: SiSupabase,
  PlanetScale: SiPlanetscale,
  Neo4j: SiNeo4J,
  Elasticsearch: SiElasticsearch,
  Meilisearch: SiMeilisearch,

  // Cloud Providers
  AWS: SiAmazonwebservices,
  "Google Cloud": SiGooglecloud,
  "Oracle Cloud": SiOracle,
  DigitalOcean: SiDigitalocean,
  Heroku: SiHeroku,
  Vercel: SiVercel,
  Netlify: SiNetlify,
  "Fly.io": SiFlydotio,

  // DevOps / Infrastructure
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  Terraform: SiTerraform,
  Pulumi: SiPulumi,
  Ansible: SiAnsible,
  Chef: SiChef,
  Puppet: SiPuppet,
  Helm: SiHelm,
  Istio: SiIstio,
  Consul: SiConsul,
  Vault: SiVault,
  Nomad: SiNomad,

  // CI/CD
  "GitHub Actions": SiGithubactions,
  "GitLab CI": SiGitlab,
  Jenkins: SiJenkins,
  CircleCI: SiCircleci,
  "Travis CI": SiTravisci,
  TeamCity: SiTeamcity,
  ArgoCD: SiArgo,

  // APIs & Protocols
  GraphQL: SiGraphql,
  tRPC: SiTrpc,
  "OpenAPI/Swagger": SiSwagger,
  JSON: SiJson,
  XML: SiXml,

  // Testing
  Jest: SiJest,
  Vitest: SiVitest,
  Mocha: SiMocha,
  Chai: SiChai,
  AVA: SiAvajs,
  Cypress: SiCypress,
  Selenium: SiSelenium,
  Puppeteer: SiPuppeteer,
  "Testing Library": SiTestinglibrary,
  JUnit: SiJunit5,
  PyTest: SiPytest,

  // Mobile
  "React Native": SiReact,
  Flutter: SiFlutter,
  SwiftUI: SiSwift,
  "Jetpack Compose": SiJetpackcompose,
  Ionic: SiIonic,
  Cordova: SiApachecordova,
  "Android SDK": SiAndroid,
  "iOS Development": SiIos,

  // Version Control
  Git: SiGit,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Bitbucket: SiBitbucket,
  Perforce: SiPerforce,
  SVN: SiSubversion,

  // Build Tools & Package Managers
  Webpack: SiWebpack,
  Vite: SiVite,
  Rollup: SiRollupdotjs,
  Babel: SiBabel,
  Turbopack: SiTurbo,
  npm: SiNpm,
  Yarn: SiYarn,
  pnpm: SiPnpm,
  Composer: SiComposer,
  Pip: SiPython,
  Poetry: SiPoetry,
  Maven: SiApachemaven,
  Gradle: SiGradle,

  // Operating Systems
  Linux: SiLinux,
  Ubuntu: SiUbuntu,
  Debian: SiDebian,
  Fedora: SiFedora,
  "Arch Linux": SiArchlinux,
  "Red Hat": SiRedhat,
  macOS: SiMacos,

  // Containers & Virtualization
  "Docker Compose": SiDocker,
  Podman: SiPodman,
  LXC: SiLinuxcontainers,
  OpenShift: SiRedhatopenshift,
  VMware: SiVmware,
  VirtualBox: SiVirtualbox,

  // Security & Auth
  "OpenID Connect": SiOpenid,
  JWT: SiJsonwebtokens,
  OWASP: SiOwasp,

  // Analytics & Monitoring
  Prometheus: SiPrometheus,
  Grafana: SiGrafana,
  "New Relic": SiNewrelic,
  Datadog: SiDatadog,
  Splunk: SiSplunk,
  "ELK Stack": SiElasticstack,
  Sentry: SiSentry,

  // Message Brokers & Queues
  RabbitMQ: SiRabbitmq,
  Kafka: SiApachekafka,
  "Amazon SQS": SiAmazonsqs,
  NATS: SiNatsdotio,
  "Redis Pub/Sub": SiRedis,

  // Data Science & ML
  NumPy: SiNumpy,
  Pandas: SiPandas,
  "Scikit-learn": SiScikitlearn,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  Keras: SiKeras,
  spaCy: SiSpacy,
  OpenCV: SiOpencv,

  // Big Data & Processing
  Hadoop: SiApachehadoop,
  Spark: SiApachespark,
  Hive: SiApachehive,
  Presto: SiPresto,
  Flink: SiApacheflink,
  Airflow: SiApacheairflow,

  // Misc Dev Tools
  ESLint: SiEslint,
  Prettier: SiPrettier,
  Storybook: SiStorybook,
  Figma: SiFigma,
  Postman: SiPostman,
  Insomnia: SiInsomnia,

  // Blockchain / Web3
  Solidity: SiSolidity,
  Ethereum: SiEthereum,
  "Ethers.js": SiEthers,
  "Web3.js": SiWeb3Dotjs,
  IPFS: SiIpfs,
  Polygon: SiPolygon,
  Solana: SiSolana,
};
